plugins {
    id 'com.android.application'
}

android {
    namespace 'com.doveloaimesso.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.doveloaimesso.app"
        minSdk 26
        targetSdk 34
        versionCode 284
        versionName "2.8.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ""
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.activity:activity:1.9.0'
    implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
}

